# Generated by Django 5.2.1 on 2025-05-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviemodel',
            old_name='movie_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='movie_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='moviemodel',
            old_name='movie_year',
            new_name='year',
        ),
    ]
