# Generated by Django 5.2.1 on 2025-05-23 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_movie_genre_moviemodel_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviemodel',
            name='year',
            field=models.IntegerField(),
        ),
    ]
